"""Update Table Product

Revision ID: 6c868e44a209
Revises: c388e3154488
Create Date: 2026-05-27 08:36:03.534517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c868e44a209'
down_revision = 'c388e3154488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('DateProduct', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('DateProduct')
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
