"""create all tables in mysql

Revision ID: 765442e3c874
Revises: 
Create Date: 2026-06-14 03:22:15.475467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765442e3c874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(length=100), nullable=False),
    sa.Column('Image', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('DateProduct', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=100), nullable=True),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.Column('Type_user', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Booking',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('BookingDate', sa.DateTime(), nullable=False),
    sa.Column('deliver_booking', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_table('information_user',
    sa.Column('InformationID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Phone', sa.String(length=15), nullable=False),
    sa.Column('Governorate', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Street', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('InformationID'),
    sa.UniqueConstraint('UserID')
    )
    op.create_table('Information_Booking',
    sa.Column('InformationBookingID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['BookingID'], ['Booking.BookingID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('InformationBookingID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Information_Booking')
    op.drop_table('information_user')
    op.drop_table('Booking')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
