"""Create Table InformationUser for User one to one 

Revision ID: 882dba0fd4f9
Revises: 6c868e44a209
Create Date: 2026-05-29 17:43:09.729904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882dba0fd4f9'
down_revision = '6c868e44a209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_user',
    sa.Column('InformationID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Phone', sa.Integer(), nullable=False),
    sa.Column('Governorate', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Street', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('InformationID'),
    sa.UniqueConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information_user')
    # ### end Alembic commands ###
