"""Update Database

Revision ID: c388e3154488
Revises: 
Create Date: 2026-05-23 03:55:57.181270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c388e3154488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('Booking',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('BookingDate', sa.DateTime(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID', 'UserID', 'ProductID')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type_user', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Type_user')

    op.drop_table('Booking')
    op.drop_table('product')
    # ### end Alembic commands ###
