"""Updated Table User for add Column Image.

Revision ID: ebee9fdf42da
Revises: 882dba0fd4f9
Create Date: 2026-05-29 17:50:47.995172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebee9fdf42da'
down_revision = '882dba0fd4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
